version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - challenge-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - challenge-app
    volumes:
      - mongo-data:/data/db

networks:
  challenge-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    